name: Build and test
on:
  pull_request:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install meson build
        run: |
          pipx install meson
          pipx install ninja

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          meson setup build
          ninja -C build

      - name: Run tests
        run: |
          meson test -C build

      # - name: Convert test results
      #   if: success() || failure()
      #   run : |
      #     ninja -C build test/test-results.xml

      - name: Test report (phoenix-actions)
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: JEST
          path: build/*.xml
          reporter: jest-junit

      - name: Test report (phoenix-actions)
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: Java JUnit
          path: build/*.xml
          reporter: java-junit

      - name: Test report (EnricoMi)
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: success() || failure()
        with:
          check_name: Test report (publish-unit-test-result-action)
          files: "build/*.xml"
          comment_mode: off

      - name: Test report (mikepenz)
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: action-junit-report
          report_paths: 'build/*.xml'
