name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install meson build
        run: |
          pipx install meson
          pipx install ninja

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          meson setup build
          ninja -C build

      - name: Run tests
        run: |
          meson test -C build --test-args=--ascii

      - name: Convert test results
        if: success() || failure()
        run : |
          ninja -C build test/test-results.xml

      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 5
          path: build/**/*.xml

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: JEST Tests
          path: build/*.xml
          reporter: jest-junit
