name: Release
on:
  release:
    types: [created, published]


jobs:
  publish:
    environment:
      name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check release
        run: |
          echo ${{ github.event.release.assets }}
          echo ${{ github.event.release.tarball_url }}
